# Generated by Django 5.2.8 on 2025-11-29 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
